Src/RecruitmentTask.Web/Controllers/EmployeeDetailsController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using RecruitmentTask.Infrastructure.Services;

namespace RecruitmentTask.Web.Controllers
{
    public class EmployeeDetailsController : Controller
    {
        private readonly IEmployee _employee;
        public EmployeeDetailsController(IEmployee employee)
        {
            _employee = employee;
        }
        // GET: EmployeeDetails
        public async Task<ActionResult> Index(int id, string firstName, string lastName)
        {
            var details = await _employee.GetDetails(id, firstName, lastName);
            return View(details);
        }
    }
}

Src/RecruitmentTask.Web/Controllers/EmployeesController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using RecruitmentTask.Infrastructure.Services;
using RecruitmentTask.Core.Extensions;

namespace RecruitmentTask.Web.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly IEmployees _employees;
        public EmployeesController(IEmployees employees)
        {
            _employees = employees;
        }
        // GET: Employees
        
        public async Task<ActionResult> Index(int? page)
        {
            int pageNumber = page == null ? 1 : (int)page;
            var pageData = await _employees.GetPage(pageNumber);

            return View(pageData);
        }

        [HttpGet]
        public async Task<ActionResult> ByJobItle(int? page, string jobTitle)
        {
            if(!jobTitle.HasValue())
            {
                return Redirect("/Employees/Index");
            }
            int pageNumber = page == null ? 1 : (int)page;
            var pageData = await _employees.GetPageByJobTitle(pageNumber, jobTitle);

            return View("Index", pageData);
        }
    }
}

Src/RecruitmentTask.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace RecruitmentTask.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Src/RecruitmentTask.Web/Views/EmployeeDetails/Index.cshtml
@model RecruitmentTask.Core.Model.EmployeeDetails

@{
    ViewBag.Title = "Employee Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<table class="table">
    <thead>
        <tr>
            <th scope="col" colspan="2">@Model.FirstName @Model.LastName</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>JobTitle</td>
            <td>@Model.JobTitle</td>
        </tr>
        <tr>
            <td>PhoneNumber</td>
            <td>@Model.PhoneNumber</td>
        </tr>
        <tr>
            <td>Salary</td>
            <td>@Model.Salary</td>
        </tr>
        <tr>
            <td>Day Of Employment</td>
            <td>@Model.DayOfEmployment</td>
        </tr>
        <tr>
            <td>Address</td>
            <td>@Model.Address.City @Model.Address.Street @Model.Address.HouseNumber</td>
        </tr>
        <tr>
            <td>URLS</td>
            <td>
                <ul>
                    @foreach (var item in Model.Links)
                    {
                        <li><a href="@item.Href">@item.Href</a></li>
                    }
                </ul>
            </td>
        </tr>
    </tbody>
</table>
<br />
<nav aria-label="Page navigation example">
    <ul class="pagination">
            <li class="page-item">
                <a class="page-link" href="@Request.UrlReferrer" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Back to previous page</span>
                </a>
            </li>
        </ul>
</nav>

Src/RecruitmentTask.Web/Views/Employees/Index.cshtml
@model RecruitmentTask.Core.Model.PageData

@{
    ViewBag.Title = "Employee List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}<div>
     <form method="get" action="@Url.Action("ByJobItle", "Employees")">

         <select name="jobTitle">
             <option value="">All</option>
             @foreach (var item in @Model.JobTitles)
             {
                 if (@item == @Model.JobTitle)
                 { 
                     <option value="@item" selected="selected">@item</option>
                 }
                 else
                 {
                     <option value="@item">@item</option>
                 }
             }
         </select>

         <div>
             <button type="submit" class="btn">GO</button>
         </div>

     </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Job Title</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Employees)
        {
        <tr>
            <td>
                <a href="@Url.Action("Index", "EmployeeDetails",  new { id = @item.ID, firstName = @item.FirstName, lastName = @item.LastName })">
                    @item.ID
                </a>
            </td>
            <td>@item.FirstName</td>
            <td>@item.LastName</td>
            <td>@item.JobTitle</td>
        </tr>

        }
    </tbody>
</table>
<br />
<nav aria-label="Page navigation example">
    <ul class="pagination">
        @if (Model.Current > 1)
        {
            <li class="page-item">

                <a class="page-link" href="
                   @if (string.IsNullOrEmpty(@Model.JobTitle))
                   {
                        @Url.Action("Index", "Employees", new { page = Model.Current - 1 })
                   }
                   else
                   {
                        @Url.Action("ByJobItle", "Employees", new { jobTitle = Model.JobTitle,page = Model.Current - 1 })
                   }
                   " 
                   aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
        }
        @if (Model.PageSize == Model.Employees.Count)
        {
            <li class="page-item">
                <a class="page-link" href="
                    @if (string.IsNullOrEmpty(@Model.JobTitle))
                   {
                        @Url.Action("Index", "Employees", new { page = Model.Current + 1 })
                   }
                   else
                   {
                        @Url.Action("ByJobItle", "Employees", new { jobTitle = Model.JobTitle,page = Model.Current + 1 })
                   }
                   
                   " aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
            }
        </ul>
</nav>

Src/RecruitmentTask.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
</div>

Src/RecruitmentTask.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Columbus Recruitment Task", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Employees", "", "")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>